name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: jack9005/node-app:latest   ✅
  KUBECTL_IMAGE: bitnami/kubectl:latest   ✅

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t $DOCKER_IMAGE .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    

    - name: Push Docker Image
      run: docker push $DOCKER_IMAGE

    - name: Setup Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        docker run --rm -v $HOME/.kube:/root/.kube -v $(pwd):/app -w /app $KUBECTL_IMAGE apply -f deployment.yaml
        docker run --rm -v $HOME/.kube:/root/.kube -v $(pwd):/app -w /app $KUBECTL_IMAGE apply -f service.yaml
        docker run --rm -v $HOME/.kube:/root/.kube $KUBECTL_IMAGE rollout status deployment/node-app-deployment
